### PR TITLE
Shell command options for media keys

### LINKED ISSUE #136: --pass-media-keys, --pass-screen-keys and --pass-power-keys options do not work in DEs
## This issue is a....

<pre>
[X] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

In XFCE, using `i3lock --pass-media-keys` does not pass the media keys to the desktop environment. This happens regardless if the `XF86` keys are bound in `xfce4-settings`, or through an external application such as `volumeicon`. I'm unsure why this happens, as `--pass-media-keys` works as expected in `i3`.

## Expected Behavior

`--pass-media-keys` should pass the media keys to the underlying environment, regardless of the used window manager.

## Reproduction Instructions

Install XFCE (`pacman -S xfce4`), bind `XF86AudioMute` either in keyboard settings or a program like `volumeicon`, try to mute when the screen is locked with `i3lock --pass-media-keys`.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version aur-2fd6547 (2019-09-20, branch "tags/aur-2fd6547") © 2010 Michael Stapelberg, © 2015 Cassandra Fox

</pre>

Where'd you get i3lock-color from?

<pre>
[X] AUR package (which one?)
`i3lock-color-git`
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

### PR DESCRIPTION
**Pull request by jclds139**
Closes #136 

## Description
Enables options to provide a shell command to run for each of the keys that could be passed by `--pass-*-keys`.
A master option, `--custom-key-commands` enables all of the others, then each of  `--*-cmd` corresponds to a single keysym, taking a shell command to run when that key is pressed.

This could look like a security hole, but it realistically should be no more dangerous than the existing `--pass-*-keys` options, which let the root window do whatever it wants in responds to the keypress.

## Release notes

Notes: Enables custom shell commands to handle media, power, screen, and volume keys as an alternative to passing them to the root window.

### CODE REVIEW

**Review by JezerM — COMMENTED** [review]
I suggest to change the naming to `cmd-**-**` for a better scheme, which might help to find these commands faster, like `--cmd-brightness-up` and `--cmd-power-off`.

This feature could be insecure, but yet it's opt to the user to take the risk and make sure it works with their environment. It's simpler and better than my previous solution.

**Comment by jclds139** [comment]
Good point! Done. Do you want the commits squashed together?

edit: apologies for accidentally closing the PR when commenting

File: i3lock.c [hunk 1]
```diff
@@ -2119,6 +2240,53 @@ int main(int argc, char *argv[]) {
 				pass_volume_keys = true;
 				break;
 
+            //custom key commands
+            case 609:
```
Comment (Raymo111) [inline i3lock.c]: Can you start the numbering here at 650?

**Review by Raymo111 — CHANGES_REQUESTED** [review]

**Review by jclds139 — COMMENTED** [review]
Is this acceptable? I tried to keep different key types to their own block of 10.

File: i3lock.c [hunk 2]
```diff
@@ -1558,6 +1660,25 @@ int main(int argc, char *argv[]) {
         {"pass-power-keys", no_argument, NULL, 603},
         {"pass-volume-keys", no_argument, NULL, 604},
 
+        // custom commands for pass keys
```
Comment (Raymo111) [inline i3lock.c:1663]: Hmmm in this case maybe make this 610 and the following blocks 62x, 63x, etc?

Comment (jclds139) [reply i3lock.c:1663]: I've amended it. How about now?

**Review by JezerM — DISMISSED** [review]
Looks good to me~

**Comment by Raymo111** [comment]
@jclds139 @JezerM I can't get it to work? I'm running
```
./build.sh -d
LD_PRELOAD= ./build/i3lock --no-verify --cmd-volume-up="touch /tmp/success"
```
i3lock triggers correctly, but when I press the volume up key, no file is created.

**Comment by JezerM** [comment]
You're forgetting the `--custom-key-commands` flag to enable those commands.

**Comment by Raymo111** [comment]
> You're forgetting the `--custom-key-commands` flag to enable those commands.

Thanks, I was being dumb :p

File: i3lock.c [hunk 3]
```diff
@@ -2119,6 +2240,53 @@ int main(int argc, char *argv[]) {
...
+                break;
+            case 620:
+                cmd_brightness_up = strdup(optarg);
+                break;
+            case 621:
+                cmd_brightness_down = strdup(optarg);
+                break;
+
+            case 630:
+                cmd_media_play = strdup(optarg);
```
Comment (Raymo111) [inline i3lock.c]: Why is `strdup` necessary here (same with the other uses)?

**Review by Raymo111 — CHANGES_REQUESTED** [review]
Just a quick thing about `strdup`, everything else looks great and it works very nicely!

File: i3lock.c (hunk 3 above)
Comment (jclds139) [reply i3lock.c]: It's the same as the other arguments that take a string input. `strdup` is making a new buffer containing the string. I think that's since the `optarg` buffer isn't necessarily preserved between iterations.

Comment (JezerM) [reply i3lock.c]: I thought it was because `optarg` is a global and mutable string variable. But it isn't, `optarg` seems to be changing its pointer value, so every time we access to optarg we get a different pointer, hence a different string, without modifying previous accesses to optarg. So... it looks like `strdup` is not necessary.

Comment (JezerM) [reply i3lock.c]: `strdup(optarg)` is not made in [`verif_text`](https://github.com/Raymo111/i3lock-color/blob/7668ccea3b4f73806b676a6864faaf5f7406701f/i3lock.c#L1866) and [`wrong_text`](https://github.com/Raymo111/i3lock-color/blob/7668ccea3b4f73806b676a6864faaf5f7406701f/i3lock.c#L1869), yet we have two different values for each one.

Comment (jclds139) [reply i3lock.c]: Ok, I see that. It looks like the only other `strdup(optarg)`s then are for `image_path` and `image_raw_format`.

Comment (jclds139) [reply i3lock.c]: I've made the changes, including to `image_path` and `image_raw_format`, and rebased to remove the conflicts in the completion files.

File: i3lock-bash [hunk 4]
```diff
@@ -81,6 +81,24 @@ _i3lock() {
   "--pass-screen-keys"
   "--pass-power-keys"
   "--pass-volume-keys"
+  "--custom-key-commands"
+
```
Comment (Raymo111) [inline i3lock-bash]: small nit-pick, don't add these blank lines

File: i3lock.c [hunk 5]
```diff
@@ -1636,7 +1757,7 @@ int main(int argc, char *argv[]) {
                 unlock_indicator = false;
                 break;
             case 'i':
-                image_path = strdup(optarg);
+                image_path = optarg;
```
Comment (Raymo111) [inline i3lock.c]: This was original code and is needed, add the `strdup` back

File: i3lock.c [hunk 6]
```diff
@@ -2214,7 +2382,7 @@ int main(int argc, char *argv[]) {
                 no_verify = true;
                 break;
             case 998:
-                image_raw_format = strdup(optarg);
+                image_raw_format = optarg;
```
Comment (Raymo111) [inline i3lock.c]: This was also originally there, change it back

**Review by Raymo111 — CHANGES_REQUESTED** [review]
Couple last things

File: i3lock-bash (hunk 4 above)
Comment (Raymo111) [reply i3lock-bash]: Fixed for you

File: i3lock.c (hunk 5 above)
Comment (Raymo111) [reply i3lock.c]: Fixed for you

File: i3lock.c (hunk 6 above)
Comment (Raymo111) [reply i3lock.c]: Fixed for you

**Review by Raymo111 — APPROVED** [review]
LGTM, thanks for contributing!
