### PR TITLE
Fix scaling and add multi monitor drawing

### LINKED ISSUE #69: Indicator position bug
`i3lock --indicator` looks like this:
screenshot from 2018-01-25 20-00-28

`i3lock --indicator --indpos="w:h"`:
screenshot from 2018-01-25 20-00-16

`i3lock --indicator --indpos="0:0"`:
screenshot from 2018-01-25 20-04-05

My resolution is 1920x1080 and i don't have any problems with regular version of i3lock (correctly centered).

### PR DESCRIPTION
**Pull request by Eyenseo**
This reintroduces displaying of the elements on all screens if no screen is given by argument.

Fix #69

### CODE REVIEW

File: unlock_indicator.c [hunk 1]
```diff
@@ -606,18 +608,72 @@ void init_colors_once(void) {
     colorgen_rgb(&tmp_rgb, color, &rgb16);
 }
 
-// init_fonts_once() ?
+te_expr *compile_expression(const char *const from, const char *expression, const te_variable *variables, int var_count);
```
Comment (PandorasFox) [inline unlock_indicator.c]: These prototypes should be in the .h file, or the functions should be static

File: unlock_indicator.c [hunk 2]
```diff
@@ -32,10 +32,20 @@ extern double ring_width;
 #define BUTTON_RADIUS (circle_radius)
 #define RING_WIDTH (ring_width)
 #define BUTTON_SPACE (BUTTON_RADIUS + (RING_WIDTH / 2))
-#define BUTTON_CENTER (BUTTON_RADIUS + (RING_WIDTH / 2))
 #define BUTTON_DIAMETER (2 * BUTTON_SPACE)
-#define CLOCK_WIDTH 400
-#define CLOCK_HEIGHT 200
+
+typedef struct {
```
Comment (PandorasFox) [inline unlock_indicator.c]: This struct should be in the header file

Comment (PandorasFox) [reply unlock_indicator.c]: Well, that, or there should be an additional .c/.h file for this stuff if we break it out (which is probably best, but there's so many globals in this file that it'll probably end up being a mess)

File: unlock_indicator.c [hunk 3]
```diff
@@ -6,22 +6,22 @@
  * See LICENSE for licensing information
  *
  */
+#include "unlock_indicator.h"
```
Comment (PandorasFox) [inline unlock_indicator.c]: I'm guessing that you have a linter or something - can you disable header reordering in it?

File: unlock_indicator.h [hunk 4]
```diff
@@ -1,7 +1,8 @@
-#ifndef _UNLOCK_INDICATOR_H
-#define _UNLOCK_INDICATOR_H
```
Comment (PandorasFox) [inline unlock_indicator.h]: Similar to the header reordering, there's no real need to change this define (I'm assuming this was a linter again)

**Review by PandorasFox — COMMENTED** [review]
Looks pretty good overall; I'll give them a try myself later and double check a few things

File: unlock_indicator.c (hunk 2 above)
Comment (Eyenseo) [reply unlock_indicator.c]: I included it in the c file as there is no need to make this struct public / let users of the header parse this as it is not an interface struct but a "private" one.

File: unlock_indicator.c (hunk 1 above)
Comment (Eyenseo) [reply unlock_indicator.c]: The same reason as the struct - these are functions that are not public / an interface, they are exclusively used by this file - If you still want them moved I can to that.

File: unlock_indicator.h (hunk 4 above)
Comment (Eyenseo) [reply unlock_indicator.h]: Macros with leading underscore are reserved for the standard libraries, I can change them back if it has to be done.

File: unlock_indicator.c (hunk 3 above)
Comment (Eyenseo) [reply unlock_indicator.c]: OK - I will wait with the push until I know what you want me to do regarding the oder comments.

File: unlock_indicator.c (hunk 2 above)
Comment (PandorasFox) [reply unlock_indicator.c]: I still put things like the rgb structs into the header file, mostly just to keep things clean.

File: unlock_indicator.c (hunk 1 above)
Comment (PandorasFox) [reply unlock_indicator.c]: I mean, I think it should be just fine without the prototype before the function - if you need to forward declare them then the prototypes should be at the top of the .c file, but there shouldn't be a need like this.

see [here](https://github.com/Eyenseo/i3lock-color/blob/91c5a495cc0800548b227a4229edb38515030fcb/unlock_indicator.c#L224) for example - just static <func>, no prototype elsewhere

File: unlock_indicator.h (hunk 4 above)
Comment (PandorasFox) [reply unlock_indicator.h]: Yeah, I personally kinda disagree with it, but it's something from upstream that I'm not too interested in changing (since if they decide to change it later, it'll make merging easier)

Comment (PandorasFox) [reply unlock_indicator.h]: (that actually goes for a lot of things - I'd been making some choices to leave some stuff as-is just to make merges / keeping up-to-date with upstream easier)

File: unlock_indicator.c [hunk 5]
```diff
@@ -205,21 +202,19 @@ static cairo_font_face_t *font_faces[5] = {
  * Pro 13" Retina screen, the scaling factor is 227/96 = 2.36.
  *
  */
-static double scaling_factor(void) {
-    const int dpi = (double) screen->height_in_pixels * 25.4 /
-                    (double) screen->height_in_millimeters;
-    return (dpi / 96.0);
+static double calculate_scaling_factor(void) {
+    const double dpi = (double)screen->height_in_pixels * 25.4 /
```
Comment (PandorasFox) [inline unlock_indicator.c:206]: This needs to be changed back to an `int`.

I did some testing and with this as a double, my laptop ends up with a scaling factor of `1.00000985` instead of just `1.000...`. Looks like we don't want the extra precision here, I guess.

File: unlock_indicator.c [hunk 6]
```diff
@@ -606,18 +595,69 @@ void init_colors_once(void) {
     colorgen_rgb(&tmp_rgb, color, &rgb16);
 }
 
-// init_fonts_once() ?
+te_expr *compile_expression(const char *const from, const char *expression, const te_variable *variables, int var_count) {
```
Comment (PandorasFox) [inline unlock_indicator.c:598]: this should be `static te_expr *compile_expression(...`

File: unlock_indicator.c [hunk 7]
```diff
@@ -606,18 +595,69 @@ void init_colors_once(void) {
...
+    int te_err = 0;
+    te_expr *expr = te_compile(expression, variables, var_count, &te_err);
+    if (te_err) {
+        fprintf(stderr, "Failed to reason about '%s' given by '%s'\n", expression, from);
+        exit(1);
+    }
+    return expr;
+}
+
+DrawData create_draw_data() {
```
Comment (PandorasFox) [inline unlock_indicator.c:608]: static

File: unlock_indicator.c [hunk 8]
```diff
@@ -606,18 +595,69 @@ void init_colors_once(void) {
...
+    DrawData draw_data;
+    memset(&draw_data, 0, sizeof(DrawData));
+
+    return draw_data;
+}
+
+void draw_elements(cairo_t *const ctx, DrawData const *const draw_data) {
```
Comment (PandorasFox) [inline unlock_indicator.c:615]: static

File: unlock_indicator.c [hunk 9]
```diff
@@ -667,269 +708,233 @@ xcb_pixmap_t draw_image(uint32_t *resolution) {
...
-            iy = 0;
-            ix = te_eval(te_ind_x_expr);
-            iy = te_eval(te_ind_y_expr);
-        }
-        else {
-            ix = xr_resolutions[screen_number].x + (xr_resolutions[screen_number].width / 2);
-            iy = xr_resolutions[screen_number].y + (xr_resolutions[screen_number].height / 2);
+    double radius = (circle_radius + ring_width);
+    int button_diameter_physical = ceil(scaling_factor * BUTTON_DIAMETER);
+    DEBUG("scaling_factor is %.f, physical diameter is %d px\n",
```
Comment (PandorasFox) [inline unlock_indicator.c:825]: To figure out that weird issue with my scaling factor not being 1, I had to change this to `%f` instead of `%.f` - honestly, probably a good change to include.
